version: '3'

tasks:
  copy-plugins:
    desc: Copy active plugin assets to docs/plugins/
    cmds:
      - |
        for plugin in $(grep -E '^\s+-\s+\w' plugins.yaml | sed 's/.*- //'); do
          mkdir -p "docs/plugins/$plugin"
          [ -f "plugins/$plugin/$plugin.js" ] && cp "plugins/$plugin/$plugin.js" "docs/plugins/$plugin/"
          [ -f "plugins/$plugin/$plugin.css" ] && cp "plugins/$plugin/$plugin.css" "docs/plugins/$plugin/"
        done

  build:
    desc: Build a markdown file to HTML using pandoc
    vars:
      INPUT: '{{.INPUT | default "docs/posts/2026-01-24/index.md"}}'
    cmds:
      - pandoc {{.INPUT}} -o {{.INPUT | replace ".md" ".html"}} --standalone --from markdown --to html5 --template=src/template.html --lua-filter=src/abcjs-passthrough.lua
    sources:
      - '{{.INPUT}}'
      - src/template.html
      - src/abcjs-passthrough.lua

  build-all:
    desc: Build all markdown files in docs/posts/ to HTML
    deps:
      - copy-plugins
    cmds:
      - for f in docs/posts/*/index.md; do task build INPUT="$f"; done
    silent: true

  generate-index:
    desc: Generate docs/index.html from posts folders
    cmds:
      - python3 src/generate_index.py

  serve:
    desc: Launch livereload server for development
    cmds:
      - python -c "from livereload import Server; server = Server(); server.watch('docs/posts/**/*.md', 'task build-all'); server.watch('docs/**/*.html'); server.watch('plugins/**/*.js', 'task copy-plugins'); server.watch('plugins/**/*.css', 'task copy-plugins'); server.watch('src/*.lua', 'task build-all'); server.serve(root='docs', port=8000, host='0.0.0.0')"

  watch:
    desc: Watch and rebuild .md files as they are edited using entr
    cmds:
      - find docs/posts -name '*.md' | entr -r task build-all

  dev:
    desc: Run both livereload server and file watcher
    deps:
      - serve
